### ISSUE TITLE
Cannot change size of existing swap file

### ISSUE THREAD

**Issue by mbrodala** [petems/petems-swap_file#13] opened 2015-02-11 08:09 UTC
Once a swap file exists, trying to change its size via `swapfilesize` does not yield any changes. This is due to the module only checking for existence of the swap file, not its current size.

**Comment by petems** [comment] 2015-03-17 10:05
Hi @mbrodala! Yes, I'm looking to fix this, but the problem is it gets a bit sticky with changing pre-existing files, I don't want the module to delete anything unless specifically asked for!

I might add a "force" option to change file that already exists :+1:

**Comment by mbrodala** [comment] 2015-03-17 10:18
Do you need to delete swap files if you want to change their size? Reading the current size should be doable in any case.

**Comment by petems** [comment] 2015-03-17 10:27
Yeah, I meant not delete but modify existing files. Using the exec plus file is a lot harder to check when things change. 

I'm looking for a `dd` type and provider, because it would be easy to do something like:

```
dd { ''/mnt/swap.1":
  size => $swapfilesize,
}
```

Which would then change the swapfile when the size parameter changes...

For now I think a `swap_file_size` fact could be useful, that goes "If size of swap file != $swapfilesize, delete then make new file"

**Comment by petems** [comment] 2016-05-04 15:37
Fixed in #55

**Comment by petems** [comment] 2016-05-04 15:52
Actually, going to leave this open until I get #57 fixed, but works for Puppet > 4 already 👍

**Comment by petems** [comment] 2016-05-11 09:47
Closed via #61

**Closed by petems** 2016-05-11 09:47 UTC
